# Generated by Django 4.2 on 2023-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv_app', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
