# Generated by Django 4.2 on 2023-04-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv_app', '0003_user_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
