# Generated by Django 4.2 on 2023-04-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv_app', '0004_rename_email_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
