# Generated by Django 4.2 on 2023-04-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv_app', '0009_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
