# Generated by Django 4.2 on 2023-04-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rv_app', '0010_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
    ]
